apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "caliban.fullname" . }}-config
  labels:
    {{- include "caliban.labels" . | nindent 4 }}
data:
  caliban.toml: |
    {{- include "caliban.toml" . | nindent 4 }}
