{{- if and (eq .Values.mode "split") .Values.router.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "caliban.fullname" . }}-router
  labels:
    {{- include "caliban.labels" . | nindent 4 }}
    app.kubernetes.io/component: router
spec:
  minAvailable: {{ .Values.router.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "caliban.componentLabels" (dict "root" . "component" "router") | nindent 6 }}
{{- end }}
