{{- $routerTarget := ternary "standalone" "router" (eq .Values.mode "standalone") }}
{{- $cpTarget := ternary "standalone" "control-plane" (eq .Values.mode "standalone") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "caliban.fullname" . }}-router
  labels:
    {{- include "caliban.labels" . | nindent 4 }}
    app.kubernetes.io/component: router
  {{- with .Values.router.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.router.service.type }}
  selector:
    {{- include "caliban.componentLabels" (dict "root" . "component" $routerTarget) | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.router.service.port }}
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "caliban.fullname" . }}-control-plane
  labels:
    {{- include "caliban.labels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
  {{- with .Values.controlPlane.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.controlPlane.service.type }}
  selector:
    {{- include "caliban.componentLabels" (dict "root" . "component" $cpTarget) | nindent 4 }}
  ports:
    - name: admin
      port: {{ .Values.controlPlane.service.port }}
      targetPort: admin
      protocol: TCP
